# fly.toml app configuration file generated for pipe-server on 2023-07-20T17:47:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pipe-server"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source="pipe_server_volume"
  destination="/data"

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_PATH = "/data/mycelial.db"
