name: Deploy 

on: push
#   branches:
#     - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  NO_COLOR: 1

jobs:
  deploy-server:
    name: deploy pipe server
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          cd server 
          cargo vendor 
          make deploy_at_flyio

  deploy-client:
    name: deploy pipe client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          cd client 
          cargo vendor 
          make deploy_at_flyio
